### PR TITLE
Pin dependency versions

### PR DESCRIPTION
**Pull request by com4**
This is just a recommendation. Feel free to close or edit as needed.

- Pins dependency versions to their current latest. This should prevent future version from
  unexpectedly breaking when an upstream package makes incompatible changes.
- Move doc/test dependencies to setup.py `extra_require`. These can be installed with:
  `pip install -e ".[docs,tests]"` instead of -r requirements.txt
- Updates docker compose to have services listen on loopback (default is all addresses exposing them
  to the greater network)

### CODE REVIEW

**Comment by com4** [comment]
Github has a feature that scans dependencies in setup.py for security vulnerabilities which might be useful to turn on if you decide to keep the version pinned. It will notify you of problems and optionally opens a pull request which does the upgrade.

**Comment by marcosschroh** [comment]
Thanks @com4 for the PR.

I am not sure that pin dependencies is a good idea because this project is an open-source project and [It is not considered best practice](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires)

>  This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

I was thinking to at least use range for the requirements, for example `httpx>0.14.1`

What do you think?

**Comment by com4** [comment]
While it's not necessarily ideal to pin versions it is a bit more practical and i think it's more common[1][2]. The goal here is to provide a bit of stability. Your specific example with httpx is where the issue comes in. Since httpx isn't a 1.0 release it's going to have breaking changes in minor versions. We know that 0.13 won't work with the version of the client and we don't know that 0.15 will (if we use the 0.13 -> 0.14 as the baseline, it _will_ break).

How about httpx and fastavro get pinned at their minor version since their API presumably isn't stable, and faust can be more permissive:
```
httpx>=0.14,<0.15     # any 0.14
fastavro>=0.24,<0.25  # any 0.24
faust<2               # any 1.0
```

The test and documentation dependencies we can leave open if you prefer since they really shouldn't break anyone's production environment.

1. https://github.com/robinhood/faust/blob/master/requirements/default.txt
2. https://github.com/encode/httpx/blob/master/setup.py#L57-L64

**Comment by marcosschroh** [comment]
> How about httpx and fastavro get pinned at their minor version since their API presumably isn't stable, and faust can be more permissive

Yes, I like your idea. Also, I think is good as well to not pin `test` and `documentation` dependencies. Let's go for it!

**Comment by marcosschroh** [comment]
Awesome! Thanks

**Pull request merged**
