### PR TITLE
Feat/add json schemas

### LINKED ISSUE #99: JSON Schema support
**Is your feature request related to a problem? Please describe.**
I was wondering if support for JSON schemas was something you would be interested in having added? We are currently using confluent kafka and the schema registry to manage json schemas. We are using faust to process the data using the schema registry, and would love to be able to utilize and contribute to this library. Notably json schema support for the `FaustSerializer` would be great.

I would be happy to work with you to try submit a pull request. I would value guidance on your thoughts of how it should work and what the major changes might be.

As I see it the following is probably a good start.
* Abstract most of what is currently `AvroSchema` class into a new abstract base class and create new child classes `AvroSchema` and `JsonSchema`. Also make `load` and `async_load` static methods respectively on the classes.
* Update the serializer classes and factory. Open to ideas on exactly what should be updated here and how it would determine between avro and json schemas. Perhaps an argument given in `__init__`? Or perhaps distinct separate classes for avro vs json serialization?
* Update all type references
* Write new tests

Currently if you try use a json schema in the serializer and call `_dumps` you get the following exception.
```
  File "d:\scratch\python-schema-registry-client\schema_registry\serializers\faust_serializer.py", line 50, in _dumps
    return self.encode_record_with_schema(self.schema_subject, self.schema, payload)  # type: ignore
  File "d:\scratch\python-schema-registry-client\schema_registry\serializers\message_serializer.py", line 73, in encode_record_with_schema
    schema_id = self.schemaregistry_client.register(subject, avro_schema)
  File "d:\scratch\python-schema-registry-client\schema_registry\client\client.py", line 252, in register
    avro_schema = AvroSchema(avro_schema)
  File "d:\scratch\python-schema-registry-client\schema_registry\client\schema.py", line 13, in __init__
  File "fastavro\_schema.pyx", line 78, in fastavro._schema.parse_schema
  File "fastavro\_schema.pyx", line 254, in fastavro._schema._parse_schema
fastavro._schema_common.UnknownType
```

**Describe the solution you'd like**
I would like to be able to pass json schemas to the `FaustSerializer` and have it serialize and deserialize objects correctly without an exception.

e.g. something like.

`serializer = FaustSerializer(schema_registry_client, type(MyClass).__name__, MyClass.schema_json())`
`serializer._dumps(MyClass())`

### PR DESCRIPTION
**Pull request by Robospecta**
resolves #99 

Added support for JSON schemas. There is a couple tests that could not be reproduced for json schemas given they were unique to how avro schemas work. I have tried my best to ensure documentation and tests are up to date. There is some additional refactoring I would have liked to have made, but where possible I usually aired on the side of leaving as is and not introducing breaking changes. Hopefully for the vast amount of users they should be able to continue to use this library as is.

### CODE REVIEW

**Comment by Robospecta** [comment]
Hi @marcosschroh,

Just noting that the `test_dumps_load_message_union_avro_schema` unit test also fails for me in your master branch. When I made these changes I believe all tests were passing. Now I experience this test failing in both your master branch and my feature branch. Because it is failing in your master branch also I imagine it is unlikely to be related to my changes. Given your experience with avro schemas and developing the original tests I will leave it to you fix this if desired.

Cheers

**Comment by marcosschroh** [comment]
> Hi @marcosschroh,
> 
> Just noting that the `test_dumps_load_message_union_avro_schema` unit test also fails for me in your master branch. When I made these changes I believe all tests were passing. Now I experience this test failing in both your master branch and my feature branch. Because it is failing in your master branch I imagine it is unlikely to be related to my changes. Given your experience with avro schemas and developing the original tests I will leave with you. Please let me know if anymore changes are needed. 🙂
> 
> Cheers

Thanks. I have fixed the test. Now there is an issue with the `lint`

**Comment by Robospecta** [comment]
Hey @marcosschroh.

I believe I've fixed the linting errors. Let's see if the workflow runs without problem this time 👍

**Comment by marcosschroh** [comment]
Amazing @Robospecta . Thanks for this feature!

**Comment by Robospecta** [comment]
No problem! Thanks for accepting and your help along the way 🙌

**Pull request merged**
