### PR TITLE
chore(client): Add HTTP code in get_compatibility exception

### PR DESCRIPTION
**Pull request by vmercierfr**
Thanks for you work on this project!
I'm using your project for Kafka schema provisioning and want to fix a small issue.

# Actual Behavior

When no compatibility mode is defined for a subject (eg. after schema creation), schema registry returns 404 HTTP error. Unfortunately HTTP code 404 is not provided in `ClientError` exception so we can't deal with this case.

# Expected Behavior

In this Pull Request, I'm adding the HTTP code to the exception so we can use it to manage exceptions.

# Steps to Reproduce the Problem

Here is a small code to reproduce this issue:

```bash
>>> SCHEMA_REGISTRY_URL='http://kafka-schema-registry.dev'
>>> SUBJECT = 'my_subject'
>>>
>>> from schema_registry.client import SchemaRegistryClient
>>> from schema_registry.client.errors import ClientError
>>>
>>> client = SchemaRegistryClient(SCHEMA_REGISTRY_URL)
>>>
>>> try:
...     compatibility = client.get_compatibility(SUBJECT)
... except Exception as error:
...     print(error.http_code)
None
```

Full exception:

```
>>> compatibility = client.get_compatibility(SUBJECT)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/schema_registry/client/client.py", line 425, in get_compatibility
    f"Unable to fetch compatibility level. Error code: {code}"
schema_registry.client.errors.ClientError: Unable to fetch compatibility level. Error code: 404
```

Schema registry logs:

```
[2019-05-29 13:39:25,028] INFO 172.17.0.9 - - [29/May/2019:13:39:25 +0000] "GET /config/my_subject HTTP/1.1" 404 51  2 (io.confluent.rest-utils.requests)
```

# Proposition

With this PR, `http_code` is filled with schema registry HTTP error code and can be use in exception processing:

```
>>> SCHEMA_REGISTRY_URL='http://kafka-schema-registry.dev'
>>> SUBJECT = 'my_subject'
>>>
>>> from schema_registry.client import SchemaRegistryClient
>>> from schema_registry.client.errors import ClientError
>>>
>>> client = SchemaRegistryClient(SCHEMA_REGISTRY_URL)
>>>
>>> try:
...     current_compatibility = client.get_compatibility(SUBJECT)
... except ClientError as error:
...     if error.http_code == 404:
...         current_compatibility = None
...     else:
...         raise Exception('Client error')
... except Exception as error:
...     raise error
... 
>>> current_compatibility
>>> print(current_compatibility)
None
```

Can you consider this PR?

Thanks.

### CODE REVIEW

**Comment by marcosschroh** [comment]
Hi @vmercierfr 

You're welcome. Nice catch!! Definitely we need this!! Nice that more people is getting involved!!

We need to fix the `black` check and we can merge it. https://travis-ci.org/marcosschroh/python-schema-registry-client/jobs/538788668

**Comment by marcosschroh** [comment]
You can run `black schema_registry/client/client.py` to fix it!

**Comment by marcosschroh** [comment]
Thanks @vmercierfr . Published in the new version `0.2.3`

**Comment by vmercierfr** [comment]
Thank you very much for the merge and your work on this library!

**Pull request merged**
